---
- name: install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: latest
  notify: service

- name: create filebeat config
  ansible.builtin.template:
    src: templates/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
  notify: service

- name: Flush handlers
  meta: flush_handlers
...
