---
- name: install applications
  ansible.builtin.yum:
    name:
      - java-1.8.0-openjdk
      - logstash
    state: latest
  notify: service

- name: place logstash processing template
  ansible.builtin.template:
    src: templates/logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
    force: yes
  notify:
    - service
    - firewall

- name: set service listening address
  ansible.builtin.lineinfile:
    dest: /etc/logstash/logstash.yml
    regexp: ^http.host
    insertafter: "^# http.host"
    line: "http.host: {{ ansible_default_ipv4.address | quote }}"
  notify: service

- name: Flush handlers
  meta: flush_handlers
...
