---
- name: install kibana
  ansible.builtin.yum:
    name: kibana
    state: latest
  notify: service

- name: set kibana server address
  ansible.builtin.lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: '#server.name'
    insertafter: "^#server.host"
    line: "server.host: \"{{ ansible_default_ipv4.address }}\""
  notify:
    - service
    - firewall

- name: set elasticsearch node address
  ansible.builtin.lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: '#elasticsearch.hosts'
    insertafter: "^#elasticsearch.hosts"
    line: "elasticsearch.hosts: http://{{ ansible_default_ipv4.address }}:9200"
  notify: service

- name: Flush handlers
  meta: flush_handlers
...
